WORKING_DIRECTORY: "/home/galimimus/IdeaProjects/phishingMonitor"
USER_EMAIL: "arkadijvasilevic42@gmail.com"
USER_APP_PASS: "rghn uyaa ieym tnid"
DB_NAME: "monitor"
DB_HOST: "localhost"
DB_USERNAME: "galimimus"
DB_PASS: "pass111"
HTTP_SERVER_HOST: "192.168.3.4"
HTTP_SERVER_PORT: 8000
HTTP_SERVER_URL_HANDLE: "loh"
HTTP_SERVER_EXE_HANDLE: "secure"
HTTP_SERVER_DOWNLOAD_HANDLE: "log"
MAIL_SMTP_SERVER: "smtp.gmail.com"
MAIL_SMTP_PORT: 465
MINGW_COMMAND: "x86_64-w64-mingw32-g++"